# Generated by Django 2.0.6 on 2019-06-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('book_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'd_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DOrderltem',
            fields=[
                ('shop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shop_num', models.CharField(max_length=20)),
                ('total_price', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'd_orderltem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_moblie', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=20)),
                ('book_publish', models.CharField(max_length=20)),
                ('publish_time', models.CharField(blank=True, max_length=20, null=True)),
                ('revision', models.CharField(blank=True, max_length=20, null=True)),
                ('book_isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('word_count', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.CharField(blank=True, max_length=20, null=True)),
                ('open_count', models.CharField(blank=True, max_length=20, null=True)),
                ('book_paper', models.CharField(blank=True, max_length=20, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=20, null=True)),
                ('book_price', models.FloatField(blank=True, null=True)),
                ('book_dprice', models.FloatField(blank=True, null=True)),
                ('editor_recomme', models.TextField(blank=True, null=True)),
                ('content_introdu', models.TextField(blank=True, null=True)),
                ('author_introd', models.TextField(blank=True, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('media_review', models.TextField(blank=True, null=True)),
                ('digest_image', models.TextField(blank=True, null=True)),
                ('product_image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('series_name', models.CharField(blank=True, max_length=20, null=True)),
                ('printing_time', models.CharField(blank=True, max_length=200, null=True)),
                ('impression', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_socre', models.CharField(blank=True, max_length=20, null=True)),
                ('shelves_date', models.DateField(blank=True, null=True)),
                ('book_status', models.CharField(blank=True, max_length=20, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('num', models.CharField(blank=True, max_length=20, null=True)),
                ('create_date', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 't_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=20)),
                ('user_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loreg_app.TBook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loreg_app.TUser')),
            ],
            options={
                'db_table': 'shoppingcart',
                'managed': True,
            },
        ),
    ]
